###########################################################################################################################
#   Tests for get_youtube_cookies() in Utils/AWS_Secrets.                                                                #
###########################################################################################################################

###########################################################################################################################
####################################################     LIBRARIES     ####################################################
###########################################################################################################################

from __future__ import annotations

import os
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

import Utils.Constants as CONST
import Utils.AWS_Secrets as AWS_Secrets
from Tests.Helpers.helpers import _color_error_message_in_red

###########################################################################################################################
#################################################     INITIALIZATIONS     #################################################
###########################################################################################################################

class Test_Get_Youtube_Cookies(unittest.TestCase):

    def test_get_youtube_cookies_writes_file_and_returns_uri(self) -> None:

        """
        Test that get_youtube_cookies() writes cookies to disk and returns file URI on success.
        """

        cookies_text = "line1\nline2\n"

        with TemporaryDirectory() as tmp_dir:
            tmp_cookies_file = os.path.join(tmp_dir, "Youtube_Cookies.txt")

            with (
                patch("Utils.AWS_Secrets.COOKIES_ABS_PATH", tmp_cookies_file),
                patch("Utils.AWS_Secrets.boto3.session.Session") as mock_session_creator,
                patch("Utils.AWS_Secrets.print") as mock_print
            ):
                mock_session = mock_session_creator.return_value
                mock_client = mock_session.client.return_value
                mock_client.get_secret_value.return_value = {"SecretString": f"  {cookies_text}  "}

                result = AWS_Secrets.get_youtube_cookies()

            saved_text = Path(tmp_cookies_file).read_text(encoding = "utf-8")
            self.assertEqual(
                saved_text,
                cookies_text.strip(),
                _color_error_message_in_red(
                    f'The cookies file generated by "get_youtube_cookies()" function should contain ' +
                    f'"{cookies_text.strip()}" instead of "{saved_text}".'
                )
            )

            expected_path = Path(tmp_cookies_file).resolve().as_uri()
            self.assertEqual(
                result,
                expected_path,
                _color_error_message_in_red(
                    f'The "get_youtube_cookies()" function should return "{expected_path}" instead of "{result}".'
                )
            )

            mock_session.client.assert_called_once_with(
                service_name = "secretsmanager",
                region_name  = CONST.AWS_REGION
            )

            mock_client.get_secret_value.assert_called_once_with(SecretId = CONST.YT_COOKIES_SECRET_NAME)
            
            count = 1
            self.assertEqual(
                mock_print.call_count,
                count,
                _color_error_message_in_red(
                    f'Exactly "{count}" logging message should have been printed in terminal instead of ' +
                    f'"{mock_print.call_count}".'
                )
            )

    #######################################################################################################################
    #######################################################################################################################

    def test_get_youtube_cookies_returns_none_when_secret_is_empty(self) -> None:

        """
        Test that get_youtube_cookies() returns None when SecretString is empty.
        """

        with (
            patch("Utils.AWS_Secrets.boto3.session.Session") as mock_session_creator,
            patch("Utils.AWS_Secrets.print") as mock_print
        ):
            mock_session = mock_session_creator.return_value
            mock_client = mock_session.client.return_value
            mock_client.get_secret_value.return_value = {"SecretString": "   "}

            result = AWS_Secrets.get_youtube_cookies()

        self.assertIsNone(
            result,
            _color_error_message_in_red(
                f'The "get_youtube_cookies()" function should return "None" instead of "{result}" when the retrieved ' +
                f'secret is an empty string.'
            )
        )

        count = 1
        self.assertEqual(
            mock_print.call_count,
            count,
            _color_error_message_in_red(
                f'Exactly "{count}" logging message should have been printed in terminal instead of ' +
                f'"{mock_print.call_count}".'
            )
        )

    #######################################################################################################################
    #######################################################################################################################

    def test_get_youtube_cookies_returns_none_when_secret_is_empty_json(self) -> None:

        """
        Test that get_youtube_cookies() returns None when SecretString is '{}'.
        """

        with (
            patch("Utils.AWS_Secrets.boto3.session.Session") as mock_session_creator,
            patch("Utils.AWS_Secrets.print") as mock_print
        ):
            mock_session = mock_session_creator.return_value
            mock_client = mock_session.client.return_value
            mock_client.get_secret_value.return_value = {"SecretString": "{}"}

            result = AWS_Secrets.get_youtube_cookies()

        self.assertIsNone(
            result,
            _color_error_message_in_red(
                f'The "get_youtube_cookies()" function should return "None" instead of "{result}" when the retrieved ' +
                f'secret is an empty dict.'
            )
        )
    
        count = 1
        self.assertEqual(
            mock_print.call_count,
            count,
            _color_error_message_in_red(
                f'Exactly "{count}" logging message should have been printed in terminal instead of ' +
                f'"{mock_print.call_count}".'
            )
        )

    #######################################################################################################################
    #######################################################################################################################

    def test_get_youtube_cookies_returns_none_and_logs_error_on_exception(self) -> None:

        """
        Test that get_youtube_cookies() returns None and logs when AWS raises an exception.
        """

        with (
            patch("Utils.AWS_Secrets.boto3.session.Session") as mock_session_creator,
            patch("Utils.AWS_Secrets.print") as mock_print,
            patch("Utils.AWS_Secrets.save_exception_to_txt") as mock_save_exception
        ):
            mock_session = mock_session_creator.return_value
            mock_client = mock_session.client.return_value
            mock_client.get_secret_value.side_effect = Exception("aws error")

            result = AWS_Secrets.get_youtube_cookies()

        self.assertIsNone(
            result,
            _color_error_message_in_red(
                f'The "get_youtube_cookies()" function should return "None" instead of "{result}" when an error is raised.'
            )
        )

        count = 1
        self.assertEqual(
            mock_print.call_count,
            count,
            _color_error_message_in_red(
                f'Exactly "{count}" logging message should have been printed in terminal instead of ' +
                f'"{mock_print.call_count}".'
            )
        )
        
        expected_title = "Retrieve_Youtube_Cookies"
        self.assertEqual(
            mock_save_exception.call_args.kwargs.get("title"),
            expected_title,
            _color_error_message_in_red(
                f'The "save_exception_to_txt()" function should have been called with the "{expected_title}" argument ' +
                f'instead of "{mock_save_exception.call_args.kwargs.get("title")}".'
            )
        )

###########################################################################################################################
#####################################################     PROGRAM     #####################################################
###########################################################################################################################

if __name__ == "__main__":
    unittest.main(buffer = True)